spring.application.name=Licoreria_backend

# Puerto (opcional, Render usa dinámico si no se define)
server.port=8080

# Usar variables de entorno
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# CORS
spring.web.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}
spring.web.cors.allowed-methods=*
